name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Build
        run: msbuild src/Tmoji.sln
