name: Build

on: [push]

jobs:
  Solution:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - uses: nuget/setup-nuget@v1
      - run: nuget restore src/Tmoji.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build
        run: msbuild src/Tmoji.sln
